### ISSUE TITLE
failed when..

### ISSUE THREAD

**Issue by StaticTemp** [YueHonghui/gotools#1]
type XX struct {
	a int
	b []int
}

func TestCopyNoPtr2(t *testing.T) {

	var src XX
	src.a = 1
	src.b = []int{1,2}

	var dst XX
	StructCopy(&dst, &src)
	if dst.a != 1 {
		t.Error("field B failed")
	}
	if dst.b[1] != 2 {
		t.Error("field C failed")
	}

	fmt.Println("dst:", dst)
}

=>dst.a = 0, dst.b=[]

I test your test sample and it success.  But why using my sample?

I known.    a. b in struct must be bigger.

**Comment by YueHonghui** [comment]
Thank you for reporting issue. I will confirm and inspect this. By the way, which go version and build flags do you use?

**Comment by YueHonghui** [comment]
@StaticTemp Hi, according to [Laws of Reflection](https://blog.golang.org/laws-of-reflection)

> There's one more point about settability introduced in passing here: the field names of T are upper case (exported) because only exported fields of a struct are settable.

Fields `a` and `b` in struct `XX` are not exported, so they are not settable, `StructCopy` just ignore fields like this.
